spring:
  application:
    name: "Account Service (Development)"

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:food_delivery_db}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: true
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  access_token_validity: 600
  refresh_token_validity: 10800
  access_secret: 3gFlvKIR783
  refresh_secret: 3gFlvKIR783


logging:
  level:
    sql: debug