spring:
  application:
    name: "Account Service"

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:food_delivery_db}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
    hibernate:
      ddl-auto: none

  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest