spring:
  application:
    name: "Kitchen Service (Development)"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    sql: debug