spring:
  application:
    name: "Kitchen Service (Test)"

#  datasource:
#    url: jdbc:mongodb://localhost:27017/order_db
#    driver-class-name:
#    username: ${POSTGRES_USERNAME}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: mongodb
#
#  data:
#    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
#      database: order_db
#      port: 27017
#      host: localhost
#      uri: mongodb://localhost:27017/order_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: ${SERVER_PORT:8082}