spring:
  application:
    name: "Kitchen Service (Test)"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

server:
  port: ${SERVER_PORT:8082}

jwt:
  access_secret: 3gFlvKIR783